services:
  db:
    image: postgres
    container_name: local_pgdb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    restart: always
    ports: 
      - 5432:5432
    volumes:
      - local_pgdata:/var/lib/postgresql
    networks:
      - db_network

  pgadmin:
    depends_on: 
      - db
    image: dpage/pgadmin4
    container_name: pgadmin_gui
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8080:80
    volumes:
      - local_pgadmin:/var/lib/pgadmin
    networks:
      - db_network

volumes:
  local_pgdata:
  local_pgadmin:

networks:
  db_network: 